name: ROS 2 CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    container:
      image: ros:humble # ROS 2 Humble Docker Image

    defaults:
      run:
        shell: bash # Ensure all commands run in Bash

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          apt update && apt install -y \
            python3-colcon-common-extensions \
            python3-rosdep \
            python3-pip \
            clang-format \
            doxygen \
            graphviz \
            libeigen3-dev \
            ros-humble-eigen3-cmake-module \
            ros-humble-rclcpp \
            ros-humble-std-msgs \
            ros-humble-sensor-msgs \
            ros-humble-nav-msgs \
            ros-humble-geometry-msgs \
            ros-humble-diagnostic-msgs \
            ros-humble-tf2-ros \
            ros-humble-ros2launch \
            ros-humble-ament-cmake \
            ros-humble-ament-cmake-gtest \
            ros-humble-ament-lint-auto \
            ros-humble-ament-lint-common \
            ros-humble-ament-cmake-cpplint \
            ros-humble-ament-cmake-cppcheck

      - name: Setup ROS 2 Environment and Dependencies
        run: |
          source /opt/ros/humble/setup.bash
          sudo rosdep init || true  # Prevent failure if already initialized
          rosdep update
          rosdep install --from-paths src --ignore-src -r -y

      - name: Run ament_cmake_lint (only source files)
        run: |
          source /opt/ros/humble/setup.bash
          # Find all CMakeLists.txt and CMake files in the src directory (excluding build/)
          find src -name "CMakeLists.txt" -o -name "*.cmake" | xargs ament_lint_cmake

      - name: Build with colcon
        run: |
          source /opt/ros/humble/setup.bash
          colcon build --event-handlers console_cohesion+

      - name: Run Tests
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --event-handlers console_cohesion+
          colcon test-result --all

      - name: Run cpplint (Code Style Check)
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-select my_package
          ament_cpplint --recursive src/my_package

      - name: Run CppCheck (Static Analysis)
        run: |
          source /opt/ros/humble/setup.bash
          colcon test --packages-select my_package
          ament_cppcheck --recursive src/my_package

      - name: Generate Doxygen Documentation
        run: |
          cd src/my_package
          doxygen Doxyfile

      - name: Upload Doxygen Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: src/my_package/docs/html/ # Ensure correct documentation folder
